### ISSUE TITLE
Implement adding actions.

### ISSUE THREAD

**Issue by ondrejvajdak** [Drison64/MyPin-Rewrite#5]

**Comment by Drison64** [comment]
Fildas97#3701 Chtěl bych slyšet tvoji představu, jak by se přidávaly akce/commands v pinu. Mám jeden nápad, ale nevím jestli by to bylo easy to use.

**Comment by ondrejvajdak** [comment]
Fildas97#3701 Chtěl bych slyšet tvoji představu, jak by se přidávaly akce/commands v pinu. Mám jeden nápad, ale nevím jestli by to bylo easy to use.
